### ISSUE TITLE
The mouse_reset function clicks when it should just move the mouse

### ISSUE THREAD

**Issue by mwobensmith** [mozilla/iris2#101]
I've noticed that, upon start of a test on Mac, we call the `mouse_reset` function to move the mouse to the upper left corner, so that the cursor does not interfere with the pattern matching required to resize the browser window.

The unexpected part is that, after the mouse move, it clicks on the Apple menu, briefly displaying the menu items. Then the `maximize_window` function is called.

I haven't debugged this deep enough to find out why the extra click is happening, but we don't want it. We just want the mouse move.

**Comment by silviuFlorin** [comment]
The fix was merged into master
