### ISSUE TITLE
Fix search_engine_can_be added test case

### ISSUE THREAD

**Issue by IonutBudeanu** [mozilla/iris2#124]
`search_engine_can_be added` is failing due to a bad alignment on a target.offset.

**Comment by tracywalker** [comment]
target offset will have to be adjust as Iris2 uses center of pattern as opposed to upper-left corner of pattern in Iris1

**Comment by IonutBudeanu** [comment]
Already fixed, thank you :)

**Comment by tracywalker** [comment]
might want to search for any other tests using offsets to ensure they are correctly adjusted.

**Comment by pavelciapa** [comment]
We have recently fixed this issue at https://github.com/mozilla/iris/issues/2718. 
If actual, already in iris/dev
