### ISSUE TITLE
When user deletes a run in Control Center, an extra request is made

### ISSUE THREAD

**Issue by mwobensmith** [mozilla/iris2#168]
If the user decides to delete a run in the runs table, it will work fine. However, I have noticed that the server receives an extra request after the delete is made. The request is for the deleted resource, which causes an internal error in the local web server because the resource is no longer present.

Example of the run in the table:

<img width="932" alt="row_item" src="https://user-images.githubusercontent.com/3019057/56396814-8bb09c80-61f5-11e9-8355-481ae6fac732.png">

The network activity when the user presses the delete button:

<img width="1117" alt="network_inspector" src="https://user-images.githubusercontent.com/3019057/56396822-9834f500-61f5-11e9-879b-f08f05132df0.png">

The terminal output that indicates what Iris' web server sees, and the corresponding error that happens when it tries to satisfy the request for a resource that no longer exists.

<img width="1199" alt="terminal" src="https://user-images.githubusercontent.com/3019057/56396894-f235ba80-61f5-11e9-8392-a2302028b4ab.png">

Is there an extra network call to "/runs/<RUN_ID>/run.json" in the handler associated with the delete button? Seems that we shouldn't need that.

**Comment by psilaghi** [comment]
Confirmed.
So, what's actually happening: the onclick event on the Delete button is getting propagated up on the parent element (in our case - the table row). Therefore, the GET call to display the run details from run.json is also executed.

**Comment by psilaghi** [comment]
Fixed in https://github.com/mozilla/iris2/pull/173.
