### ISSUE TITLE
Add DEFAULT_FIREFOX_TIMEOUT property inside of the Settings class

### ISSUE THREAD

**Issue by IonutBudeanu** [mozilla/iris2#180]
Some of the tests failing because they are using `DEFAULT_FIREFOX_TIMEOUT` property which is not implemented in the current Settings class.

**Comment by tracywalker** [comment]
There have been many new timeouts added in Iris1.  Please make sure they are all ported to Iris2

**Comment by silviuFlorin** [comment]
This is a Firefox specific property that shouldn't reside in the Settings Class
