### ISSUE TITLE
Make exact() work correctly

### ISSUE THREAD

**Issue by tracywalker** [mozilla/iris2#182]
Per [Sikuli documentation](http://doc.sikuli.org/pattern.html?highlight=exact#Pattern.exact) exact() represents .similar(1.0)  We currently have exact() as 0.99, which probably explains why we don't get color matching as expected with exact().

Also filed in Iris1;  https://github.com/mozilla/iris/issues/2920

**Comment by silviuFlorin** [comment]
Actually Sikuli returns everything > 0.99 as exact match

**Comment by tracywalker** [comment]
Hi Silviu,

From pattern.py:

'''
def exact(self):
        """Set the minimum similarity of the given Pattern object to 0.99, which means exact match is required."""
        self.similarity = 0.99
return self
'''
According to the Sikuli documentation, the above, in Iris should return self.similarity = 1.0, right?

I don't think color pattern matching, exact(), has ever worked correctly in Iris.

Besides, please see the Iris1 issue.  exact() and .similar(0.99) are throwing an error.

**Comment by mwobensmith** [comment]
Fixed
