### ISSUE TITLE
Bypass mozRunner for Windows Os's 

### ISSUE THREAD

**Issue by mariusandreifilip** [mozilla/iris2#190]
In order to use latest python 3.7 version we need to bypass Mozrunner and pass the binary of firefox directly.

**Comment by mariusandreifilip** [comment]
Test results for Windows 10 Python 3.7
Application: Firefox, Platform: win, fx_version: 67.0, fx_build_id: 20190429125729, channel: beta
Passed: 97, Failed: 3, Skipped: 11, Errors 0  -- Total: 111                     Total time: 3025.2178287506104 second(s)

The following tests did not pass:
firefox_hijacking_default_search.py
delete_history_from_url_bar_completion_list.py
set_as_default_search_engine_using_one_off_context_menu.py



Test results for windows 7 Python 3.7
Application: Firefox, Platform: win, fx_version: 67.0, fx_build_id: 201904291257
29, channel: beta
Passed: 97, Failed: 3, Skipped: 11, Errors 0  -- Total: 111Total time: 2667.4342
64421463 second(s)

The following tests did not pass:
no_crash_closing_pinned.py
regular_usage.py
search_engine_can_be_added.py


Test Results for Mac Os with Python 3.7
Application: Firefox, Platform: osx, fx_version: 67.0, fx_build_id: 20190429125729, channel: beta
Passed: 98, Failed: 2, Skipped: 11, Errors 0  -- Total: 111Total time: 3228.4391181468964 second(s)

The following tests did not pass:
not_crash_options_enabled.py
tls_authentication.py

**Comment by mwobensmith** [comment]
This appears to be fixed now. :)
