### ISSUE TITLE
Minor usability enhancements for the Control Center

### ISSUE THREAD

**Issue by mwobensmith** [mozilla/iris2#205]
Based on a meeting we had, here is a small list of changes that can make it better.

* Save vertical space.
  * Make the Iris page header smaller by reducing the height. If needed, make the header text smaller.
  * Move the runs table closer to the page header.
  * Put the runs table inside a scrollable pane, and set the default list item view to four or five.
  * Optional: if needed, we could move the "delete all" button into the space occupied by the run details section, but only as a last resort.
* Dim the Launch button after it's been clicked.
* In the tree component used to display completed tests, use ellipses to truncate long test names. Currently they are displaying outside of the component area.

**Comment by psilaghi** [comment]
fixed by #247
