### ISSUE TITLE
Incorrect use of locale property in Firefox test cases

### ISSUE THREAD

**Issue by mwobensmith** [mozilla/iris2#208]
There are two issues with current Firefox tests that specify locale. 

1. In the `details` marker, we have a field for `locale`. This should be of data type array, which then contains string(s) of supported locale(s) for this test. 

From `drag_and_drop_within_awesomebar.py`:
```
locale=[Locales.ENGLISH]
```

However, in another test, this is different. From `forget_history_test_last_5_mins.py`:

```
locale='[en-US]'
```

This data type should be array, not string. 

2. We use constants like `Locales.ENGLISH` that come from our `enums.py` file.  This constant is equal to 'en-US'. The problem with naming these constants like this is that - while fine for shorthand - it is not internationally friendly. Firefox might have a notion that English == 'en-US' but we can't make assumptions like this for others. Therefore, we should not use these general constants at the moment. We should use the normal locale strings directly.

So, to sum all of the above, the tests should be updated, e.g.:

```
locale=['en-US']
```
```
locale=['en-US', 'zh-CN', 'es-ES', 'fr', 'de', 'ar', 'ru', 'ko', 'pt-PT', 'vi', 'pl', 'tr', 'ro', 'ja']
```

**Comment by IonutBudeanu** [comment]
Updated all the locales. Changes can be found on [issue_208](https://github.com/mozilla/iris2/commit/a97d5f9571efbc089d8242e16ab9e72cda4b9390) branch.

Thank You.
