### ISSUE TITLE
Migrate Bookmark test cases.

### ISSUE THREAD

**Issue by tracywalker** [mozilla/iris2#225]
Migrate all tests, pattern directories, patterns and needed helper functions from Iris to Iris 2 for the 'bookmark' test group.

**Comment by spronoza** [comment]
add_bookmark_to_other_bookmarks.py excluded because of open_firefox_menu()

**Comment by spronoza** [comment]
add_new_bookmark_from_bookmarks_toolbar_submenu.py excluded because of open_firefox_menu()

**Comment by spronoza** [comment]
add_new_bookmark_in_mozilla_firefox_section.py excluded because of open_firefox_menu()

**Comment by spronoza** [comment]
add_new_folder_from_bookmarks_toolbar_submenu.py excluded because of open_firefox_menu() and open_bookmarks_toolbar()

**Comment by tracywalker** [comment]
We want any test cases that runs properly in Iris1 to work in Iris2. What is wrong with open_firefox_menu() and open_bookmarks_toolbar()?  Those functions should be working.  If they are causing test cases to fail in Iris2, the functions should be fixed right away.  Please file issues to fix them.

**Comment by spronoza** [comment]
open_firefox_menu() and open_bookmarks_toolbar() are absent in Iris2

**Comment by tracywalker** [comment]
Then move them over.  That is part of the process of porting test cases to Iris2.

**Comment by spronoza** [comment]
Merged into dev #422
