### ISSUE TITLE
Migrate Plugin Compatibility test cases.

### ISSUE THREAD

**Issue by tracywalker** [mozilla/iris2#232]
Migrate all tests, pattern directories, patterns and needed helper functions from Iris to Iris 2 for the 'plugin_compatibility' test group.

**Comment by spronoza** [comment]
cnn_heavy_content excluded because of change_preferences didn't work as expected

**Comment by spronoza** [comment]
nasa_tv_heavy_content excluded because of change_preferences didn't work as expected

**Comment by tracywalker** [comment]
change_preference is used in many tests, that function must be made to work correctly. Please file a new issue to address fixing it.

**Comment by tracywalker** [comment]
oh wait.  it may be related to https://github.com/mozilla/iris2/issues/253#issuecomment-493372148.  The fix should be on dev now.

**Comment by spronoza** [comment]
Merged into dev #287
