### ISSUE TITLE
Migrate Anti-tracking test cases.

### ISSUE THREAD

**Issue by tracywalker** [mozilla/iris2#233]
Migrate all tests, pattern directories, patterns and needed helper functions from Iris to Iris 2 for the 'anti_tracking' test group.

**Comment by tracywalker** [comment]
These tests are going to be moved in TestRail.  Changes here and in Iris1
 to match.

**Comment by pavelciapa** [comment]
Ok, good
Related issue from Iris1 repository: https://github.com/mozilla/iris/issues/3196

**Comment by tracywalker** [comment]
Yes, I hope you haven't started migrating that group yet. I just finished adjusting Iris1 repo.

**Comment by tracywalker** [comment]
I think that'll be ok.  oh, changes only landed on dev.  I'll merge it all to master tomorrow.
you can see the simple fix in my patch.

**Comment by pavelciapa** [comment]
oh, and test suite id changed. I see your commit. 
Anyway, I don't depend too much from Iris1 repository when porting test to Iris2

**Comment by pavelciapa** [comment]
btw, small question, do I need to copy `__init__.py ` from Iris1 test folder to Iris2 test folder?

**Comment by tracywalker** [comment]
> btw, @tracywalker small question, do I need to copy `__init__.py ` from Iris1 test folder to Iris2 test folder?

great question, looking at other completed test groups.  I think the answer is no. no need for that blank file anymore.
