### ISSUE TITLE
Control Center: locale list for test should be separated by commas

### ISSUE THREAD

**Issue by mwobensmith** [mozilla/iris2#241]
<img width="361" alt="Screen Shot 2019-05-13 at 7 04 59 PM" src="https://user-images.githubusercontent.com/3019057/57665779-22cd0200-75b2-11e9-9830-76badde5694d.png">

This is what it looks like right now. Let's throw some commas in that list.

**Comment by psilaghi** [comment]
Actually, the TestDetails page uses some obsolete code. After adding the latest logic from RunDetails page, the page looks as follows:
![test_details](https://user-images.githubusercontent.com/37327056/57709961-a94a1800-7674-11e9-852d-d6c8c72339c3.PNG)

**Comment by mwobensmith** [comment]
You are right, Paul. Let's do that. :)

**Comment by psilaghi** [comment]
This was fixed some time ago.
