### ISSUE TITLE
Fix incorrect conversions on assert_false()

### ISSUE THREAD

**Issue by tracywalker** [mozilla/iris2#248]
I've notice exists/assert_false() have been incorrectly converted into wait_vanish()/assert.   The wait_vanish()'s are not in try/except blocks. That's another discussion.  But these Iris1 exists/assert_false() checks should not have been converted the way they were.  Please see example below for correct, and much simpler, conversion method.

```
# Iris1
expected_4 = exists(history_today_sidebar_pattern, 5)
assert_false(self, expected_4, 'Time range was deleted successfully from the history sidebar.')

# converted for Iris2
expected_4 = exists(history_today_sidebar_pattern, 5)
assert expected_4 is not True, 'Time range was deleted successfully from the history sidebar.'
```

Please fix all occurrences of this mistake right away.  I've noticed them mostly in the History test group, but it could be elsewhere.

**Comment by tracywalker** [comment]
This is also correct, I believe:
```
expected_4 = exists(history_today_sidebar_pattern, 5)
assert expected_4 != True, 'Time range was deleted successfully from the history sidebar.'
```

**Comment by tracywalker** [comment]
This is also correct, I believe:
```
expected_4 = exists(history_today_sidebar_pattern, 5)
assert expected_4 not True, 'Time range was deleted successfully from the history sidebar.'
```

per PEP8: Comparisons to singletons like None should always be done with is or is not, never the equality operators.

**Comment by tracywalker** [comment]
For style consistency and ease of assert conversion, we should probably use the style:

```
expected = exists(foo_pattern, 5)
assert expected is not True, ‘Message.’
```

However, it may also be acceptable to use either of the following styles:

```
expected = exists(foo_pattern, 5) is not True
assert expected, ‘Message.’
```
or even
```
assert exists(foo_pattern, 5) is not True, ‘Message.’
```

**Comment by IonutBudeanu** [comment]
Fixed in issue_248 branch.

Thanks.
