### ISSUE TITLE
The hover() API is slightly changed in iris 2

### ISSUE THREAD

**Issue by icrisan** [mozilla/iris2#250]
Tried to port a test case from iris1 to iris2 which uses the hover() API. (e.g: test case no_glitches_in_tab_layout.py)

**iris 1** code:
                tab = find(mozilla_tab_not_focused)
                region = Region(tab.x, tab.y - 10, 220, 80)
                **region.hover(tab)**

**iris 2** code:
                tab = find(mozilla_tab_not_focused)
                region = Region(tab.x - 10, tab.y - 10, 225, 80)
                **region.hover(mozilla_tab_not_focused, align=Alignment.CENTER)**

In iris2 if we use region.hover(tab) the mouse will move its position to Location(0, 0).

NOTE: I've noticed that the Location parameter was removed from the **click** API also.

**Comment by tracywalker** [comment]
Ioana, does find() even work? What is the value of 'tab' after find(mozilla_tab_not_focused)?

**Comment by mwobensmith** [comment]
I definitely want this restored to what we had in Iris 1.0.

**Comment by icrisan** [comment]
> Ioana, does find() even work? What is the value of 'tab' after find(mozilla_tab_not_focused)?

@tracywalker the find() API does work. It returns the the location Location(804, 31).

**Comment by tracywalker** [comment]
Ioana, see if you can fix this such that it works the way it did with Iris1.  Otherwise, we'll let Matt handle it.

**Comment by mwobensmith** [comment]
@icrisan I've created branch `issue_250` with a fix. I changed the test `no_glitches_in_tab_layout.py` so that it hovers to a `Location`, as it did before. Using that branch, run that test and tell me if it works for you, and if this is satisfactory or not.

I see the same problem with all of the `Region` mouse-related APIs, as you mentioned, so whatever we do here, we can apply to the others.

**Comment by icrisan** [comment]
@mwobensmith I've tested your branch and the test is working on all the OSes. Just a PEP8 violation in the mouse.py "Missing parameter lps in docstring." but I can fix it while I will update the Region mouse-related APIs.
