### ISSUE TITLE
Some values in the CC run details are null

### ISSUE THREAD

**Issue by mwobensmith** [mozilla/iris2#252]
Values such as `passed/failed/errors `should be type `int`, but appear as `null`. Also, in the list of `params`, values that are `Boolean` appear as `null`.

<img width="911" alt="Screen Shot 2019-05-15 at 10 08 30 AM" src="https://user-images.githubusercontent.com/3019057/57794906-97f71f00-76f9-11e9-8e10-a8c6b17ee70c.png">

**Comment by psilaghi** [comment]
Should be fixed by https://github.com/mozilla/iris2/pull/264.
Matt, could you please give it a try? I only had null values for boolean props.

**Comment by mwobensmith** [comment]
Fixed - thanks @psilaghi !
