### ISSUE TITLE
Put wait_vanish inside of the try except bocks in all of the tests

### ISSUE THREAD

**Issue by IonutBudeanu** [mozilla/iris2#259]
Some of the `wait_vanish` statements are outside of the try except blocks and it will block the run if the assert will fail. Most of them are inside of the history test suite.

**Comment by tracywalker** [comment]
This is invalid.  The asserts (specifically assert_false()) in the history tests were incorrectly converted  to wait_vanish().  Please refer to https://github.com/mozilla/iris2/issues/248 for correct method of  conversion.
