### ISSUE TITLE
Fix for change_preferences

### ISSUE THREAD

**Issue by spronoza** [mozilla/iris2#263]
It seems that is no focus on edited preference

**Comment by tracywalker** [comment]
Serhii,  Can you provide more details? Steps to reproduce, screenshots, etc.  I  think this may be fixed by https://github.com/mozilla/iris2/pull/262 which is related to https://github.com/mozilla/iris2/issues/253.  However, I can't tell without further information here.

**Comment by spronoza** [comment]
`        paste(pref_name)
        time.sleep(Settings.DEFAULT_UI_DELAY)
        type(Key.TAB)
        time.sleep(Settings.DEFAULT_UI_DELAY)
        type(Key.TAB)
        time.sleep(Settings.DEFAULT_UI_DELAY)`

After the pasting preference that is need to be changed, function trying to focus on it by the pressing TAB but it is not working. Another way needed to focus on the preference that need to be changed.

**Comment by tracywalker** [comment]
Try a longer sleep time between TABs

**Comment by spronoza** [comment]
Problem is not in in sleep time. You just can't reach preferences field by hitting TABs

**Comment by tracywalker** [comment]
It worked in Iris1.

**Comment by spronoza** [comment]
Already fixed in dev branch. commit 8533e6cee4d176813bb67302e5acbc1428f0cc21
