### ISSUE TITLE
Can't detect local Firefox install if installed via scoop

### ISSUE THREAD

**Issue by mwobensmith** [mozilla/iris2#266]
On Windows, the bootstrap script installs Firefox via scoop. However, when Iris launches the Control Center, it looks for Firefox in several different directories, but won't find it unless the user has already installed it manually. 

In `path_manager.py`, `get_local_firefox_path`, we should add the location within `<user>\scoop\shims\` to use Firefox from there.

**Comment by mariusandreifilip** [comment]
fixed in issue_266 and merged to dev
