### ISSUE TITLE
Add DEFAULT_TINY_FIREFOX_TIMEOUT and DEFAULT_SHORT_FIREFOX_TIMEOUT into settings.py

### ISSUE THREAD

**Issue by paulprokhorovmoz** [mozilla/iris2#271]
Add DEFAULT_TINY_FIREFOX_TIMEOUT and DEFAULT_SHORT_FIREFOX_TIMEOUT into settings.py,

**Comment by mwobensmith** [comment]
We want to add these Firefox-specific constants to the Firefox target module, and not the core api.

Create a file here:

`targets/firefox/settings.py`

Create a class called `Settings` and add your static constants there. Then, import this module into `targets/firefox/test_dependencies.py`.
