### ISSUE TITLE
Use of set_profile_pref causes bad JSON file creation

### ISSUE THREAD

**Issue by mwobensmith** [mozilla/iris2#324]
From @pavelciapa 

> After investigation I found that having this preference:
tests/firefox/privacy/no_browsing_download_history.py

        set_profile_pref={
                          'browser.download.dir': IrisCore.get_downloads_dir(),

> I got blank test list. No matter if I deleted target.json or not. After comment out this line in this test and deleting target.json I got full test list

I will debug this and try to fix.

**Comment by mwobensmith** [comment]
@pavelciapa A couple of things:

* `IrisCore` is no longer in Iris 2. However, `PathManager` has most of those methods.
* `PathManager` is lacking the methods used to create and manage the download directories.

Additionally, because there is a reference to an undefined class `IrisCore`, the test silently fails to run, as we have configured `pytest` to suppress its output by default. You can turn it on, however, using `-i DEBUG`, and you'd see the actual test failure.

I have created a fix, but this exposes another potential problem. There is now a `downloads` folder inside the run folder, but not inside the individual test folder. This is different behavior than Iris 1. A possible side effect could be collisions of things inside the download folder, if different tests use it and expect it to be in a certain state. If that's a problem, we'll figure out another way to do this.

**Comment by mwobensmith** [comment]
Fixed in PR #325

**Comment by pavelciapa** [comment]
> 
> 
> @pavelciapa A couple of things:
> 
>     * `IrisCore` is no longer in Iris 2. However, `PathManager` has most of those methods.
> 
>     * `PathManager` is lacking the methods used to create and manage the download directories.
> 
> 

Also:
* `set_profile_pref={} `  is now `preferences={} `
