### ISSUE TITLE
Run table is limited to around 20 runs

### ISSUE THREAD

**Issue by mwobensmith** [mozilla/iris2#328]
I just noticed that only around 20 of my local runs were displayed. Is there a reasonable amount of rows that we should set this control to display? Can it support 500?

**Comment by psilaghi** [comment]
Fixed by https://github.com/mozilla/iris2/pull/356.
The react-table component has a 'defaultPageSize' prop set initially to 20 rows. I've dropped it, and now should support infinite rows, although I didn't have very big real data to test with.
