### ISSUE TITLE
Control Center: Runs with duration times of less than 1 second currently display nothing

### ISSUE THREAD

**Issue by mwobensmith** [mozilla/iris2#330]
I'm guessing that we have a glitch where the float value of a run duration is less than 1 second, and the Control Center can't handle it.

I'd like the condition of duration > 1 second to be displayed as such. We don't have to display a float - just `< 1 sec` if possible.

**Comment by psilaghi** [comment]
Fixed by https://github.com/mozilla/iris2/pull/356.
