### ISSUE TITLE
CC: Adjust column widths in runs table

### ISSUE THREAD

**Issue by mwobensmith** [mozilla/iris2#365]
The columns for `Duration` and `Completed` could use some more space, as the text on the latter is currently being truncated. We can reduce the width of the columns for `Locale` and `Total Tests` to make space.

<img width="1061" alt="Screen Shot 2019-05-29 at 6 52 31 AM" src="https://user-images.githubusercontent.com/3019057/58572843-51252100-81f1-11e9-9934-0e40ec350ec8.png">

**Comment by psilaghi** [comment]
Fixed.
