### ISSUE TITLE
CC: The text in code and call stack needs line returns

### ISSUE THREAD

**Issue by mwobensmith** [mozilla/iris2#366]
Currently this gets written to the JSON as one long line for each property. We should insert newline characters that will allow this text to display correctly in the web page.

Examples of how it looks now:

<img width="697" alt="Screen Shot 2019-05-29 at 10 24 02 AM" src="https://user-images.githubusercontent.com/3019057/58577734-f80eba80-81fb-11e9-98b5-870c16acb362.png">
<img width="692" alt="Screen Shot 2019-05-29 at 10 24 13 AM" src="https://user-images.githubusercontent.com/3019057/58577739-f9d87e00-81fb-11e9-86ce-4bedc3824101.png">

What we'd like it to look like:

**code:**
```
24: cdn77_logo_pattern = Pattern('cdn77_logo.png') 
25: cloudflare_support_page_pattern = Pattern('cloudflare_support_page.png') 
26: cloudflare_support_button_pattern = Pattern('cloudflare_support_button.png') 
27: the_regiter_log_in_button_pattern = Pattern('the_regiter_log_in_button.png') 
28: the_register_log_in_page_pattern = Pattern('the_register_log_in_page.png') 
29: cdn77_support_button_pattern = Pattern('cdn77_support_button.png').similar(.6) 
30: cdn77_support_page_pattern = Pattern('cdn77_support_page.png') 
31: 
32: navigate('https://www.cloudflare.com/') 
33: assert exists(cloudflare_logo_pattern, Settings.DEFAULT_HEAVY_SITE_LOAD_TIMEOUT), \ 
```

**call_stack:**
```
Traceback (most recent call last):
    File '/Users/mwobensmith/.local/share/virtualenvs/iris2-Fh8pD0FE/lib/python3.7/site-packages/_pytest/runner.py':225 in from_call
  result = func()

    File '/Users/mwobensmith/.local/share/virtualenvs/iris2-Fh8pD0FE/lib/python3.7/site-packages/_pytest/runner.py':197 in <lambda>
  return CallInfo.from_call(
        lambda: ihook(item=item, **kwds), when=when, reraise=reraise
    )

    File '/Users/mwobensmith/.local/share/virtualenvs/iris2-Fh8pD0FE/lib/python3.7/site-packages/pluggy/hooks.py':289 in __call__
  return self._hookexec(self, self.get_hookimpls(), kwargs)

    File '/Users/mwobensmith/.local/share/virtualenvs/iris2-Fh8pD0FE/lib/python3.7/site-packages/pluggy/manager.py':68 in _hookexec
  return self._inner_hookexec(hook, methods, kwargs)

    File '/Users/mwobensmith/.local/share/virtualenvs/iris2-Fh8pD0FE/lib/python3.7/site-packages/pluggy/manager.py':62 in <lambda>
  self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
            methods,
            kwargs,
            firstresult=hook.spec.opts.get(\"firstresult\") if hook.spec else False,
        )

    File '/Users/mwobensmith/.local/share/virtualenvs/iris2-Fh8pD0FE/lib/python3.7/site-packages/pluggy/callers.py':208 in _multicall
  return outcome.get_result()
(...)
```

**Comment by mwobensmith** [comment]
@psilaghi From the `run.json` file, I can see that these strings do contain the newline character `\n` within them. I would think, in theory, that this is enough for them to be parsed in the Control Center and displayed correctly. I'm guessing that somewhere along the way, this gets converted to HTML and we lose these characters.

<img width="870" alt="Screen Shot 2019-05-29 at 9 54 06 AM" src="https://user-images.githubusercontent.com/3019057/58575878-e4615500-81f7-11e9-873c-94fcb8076610.png">


I tried inserting a `<br>` tag inside the code directly - instead of the newline - but this does not get interpreted as HTML in the final page. I just end up seeing the `<br>` as text.

Can you parse the `\n` character in these property values and insert the HTML markup on your end, to force these lines to break? I'm not sure how else to do this. If you have another idea, please let me know.

**Comment by mwobensmith** [comment]
I did check in some code in #367 because we weren't converting the bytes to Unicode correctly, but the issue above remains.

**Comment by psilaghi** [comment]
I managed to solve the issue by using some css props which parse automatically the \n character.
We have 2 options in case of long lines: break them or display with horizontal scroll.
![code_no_scroll](https://user-images.githubusercontent.com/37327056/58631807-56b36180-82ec-11e9-80f9-0c5dc7605ee1.png)
![code_scroll](https://user-images.githubusercontent.com/37327056/58631813-5d41d900-82ec-11e9-8ca8-4181960d5b2f.png)
Let me know which one you prefer. Note that for the second image, there is a horizontal scrollbar at the end of the 'call_stack' section.

**Comment by mwobensmith** [comment]
@psilaghi Great to hear! I'd go with the second option - horizontal scroll. That seems pretty standard for displaying pre-formatted code on the web.

**Comment by psilaghi** [comment]
Fixed.
