### ISSUE TITLE
CC: Highlight area for assert button is too small with long test name

### ISSUE THREAD

**Issue by mwobensmith** [mozilla/iris2#383]
When the test name is long, the text breaks and the list item expands to fit the text. However, the highlight area that displays on mouse over is still set to the original size. See image below.

<img width="772" alt="Screen Shot 2019-05-30 at 12 51 54 PM" src="https://user-images.githubusercontent.com/3019057/58660252-de43a500-82d9-11e9-886b-23a12112c638.png">

Can we resize this area to fit the text?

**Comment by psilaghi** [comment]
Fixed.
