### ISSUE TITLE
Logic of exclude='', blocked_by=''

### ISSUE THREAD

**Issue by pavelciapa** [mozilla/iris2#391]
In Iris1 we had dict `blocked_by={id:'', platform:''}`, in Iris2 there is another logic.

for example:
```
exclude=OSPlatform.WINDOWS
blocked_by='issue_1811'
```
blocks on every platfrom not only on WINDOWS

what is correct way to block test on certain platform?

**Comment by pavelciapa** [comment]
If try leaving out `# blocked_by=‘issue_1811’` blocks, having only platform=OSPlatform.WINDOWS and it skips on osx

**Comment by mwobensmith** [comment]
Hi @pavelciapa - I've pushed a fix to branch issue_391. Please try it.

The problem - as you noted - was that we didn't keep the same logic in Iris 2 as we had before. The `blocked_by` field should be a `dict`, not a `str`. All of our test cases are currently using strings here. I have created logic that should accept both, but if the developer only uses a string, we will assume they want to block on the current platform.

So, try this:
```
    @pytest.mark.details(
        description="This is a test", blocked_by={'id':'12345', 'platform':OSHelper.WINDOWS}
    )
```

Please run this on a few tests - with/without current platform blocked, and with/without blocking issues - and tell me if it behaves as expected. If it's good, we'll have to tell the team to make sure to use the `dict` and not the `str` value here.

**Comment by pavelciapa** [comment]
+: test run without errors 

System MAC | blocking MAC | not blocking MAC
-- | -- | --
blocked_by={'id':'issue_1811', 'platform':OSPlatform.WINDOWS} |   | +
blocked_by={'id':'issue_1811', 'platform':OSPlatform.WINDOWS, OSPlatform.MAC} |   | Syntax Error
blocked_by={'id':'issue_1811', 'platform': [OSPlatform.WINDOWS, OSPlatform.MAC]} | + |  
blocked_by={'id':'issue_1811', 'platform':OSPlatform.MAC} | + |  
blocked_by={'id':'issue_1811', 'platform':OSPlatform.ALL} | + |  
blocked_by={'id':'issue_1811', 'platform': [OSPlatform.WINDOWS, OSPlatform.LINUX]} |   | +
blocked_by={'platform':OSPlatform.ALL} |   | Terminating process
blocked_by={'platform': [OSPlatform.WINDOWS, OSPlatform.MAC]} |   | KeyError: 'id'
blocked_by={'platform':OSPlatform.WINDOWS} |   | KeyError: 'id'
blocked_by={'platform':OSPlatform.MAC} |   | Terminating process
blocked_by={'platform': [OSPlatform.MAC]} |   | Terminating process
blocked_by={'id':'issue_1811'} |   | Terminating process

**Comment by pavelciapa** [comment]
Few times I had KeyError: 'id' but repeating same case terminal shown only Termitating process

**Comment by pavelciapa** [comment]
@mwobensmith  Another small question, what if we have few issues that are blocking test case?

**Comment by mwobensmith** [comment]
I will fix the issue where one uses multiple platforms in the platform field. Otherwise, it appears to be working correctly. The other cases above seem like error cases that should not work. I suppose we could do a better job handling them, however.

> @mwobensmith Another small question, what if we have few issues that are blocking test case?

Please file new issues or send me questions privately for those. Thank you.
