### ISSUE TITLE
Cannot run test cases on OSX for MacBooks

### ISSUE THREAD

**Issue by nevdokimov** [mozilla/iris2#397]
Cannot run test cases on OSX for MacBooks.
When I run any test from Control Center it opens Firefox, but Iris doesn't resize it to full screen.
Then nothing happens for some time and Iris closes Firefox with Assertion Error of first step in a test case. 
It happens for every test case and only for OSX Mojave for MacBooks.

```
        web_page_loaded_exists = exists(LocalWeb.SOAP_WIKI_SOAP_LABEL, FirefoxSettings.SITE_LOAD_TIMEOUT)
>       assert web_page_loaded_exists is True, 'The website in question is properly loaded.'
E       AssertionError: The website in question is properly loaded.
E       assert False is True

../iris2/tests/firefox/content_scroll/zoomed_in_out.py:30: AssertionError
```

**Comment by tracywalker** [comment]
I have been stuck because of this on my macOS Mojave laptop too. I thought it was just me.

**Comment by mwobensmith** [comment]
I will look at this shortly. For what it's worth, I am able to run Iris fine on my MacBook with Mojave.

**Comment by paulprokhorovmoz** [comment]
@tracywalker Have a look in Security Preferences > Security & Privacy > Privacy > Accessibility - you might have to allow your terminal application (e.g. PyCharm) in the list.

**Comment by tracywalker** [comment]
I just Iris from Terminal.  I looked to see if my terminal was listed in the system pref that you mentioned.  It was there.  However, it was not "Checked." So I corrected that and added PyCharm.  

That worked!  Iris runs tests!

We'll need to document this.  

Thank you Paul.

**Comment by mwobensmith** [comment]
This will be added somewhere in the setup document, along side common support issues.
