### ISSUE TITLE
Crash reporter does not show after crashing Firefox

### ISSUE THREAD

**Issue by pavelciapa** [mozilla/iris2#403]
In private browsing test I have to crash Firefox, but I don't get crash reporter with option "restart"
https://testrail.stage.mozaws.net/index.php?/cases/view/101748

@mwobensmith , How to enable crash reporter window now? Thanks 

Can't pass show_crash_reporter args to FirefoxRunner(), as it was in  **Iris 1** 
```
        restart_firefox(self,
                        self.browser.path,
                        self.profile_path,
                        self.base_local_web_url,
                        show_crash_reporter=True)
```

**Comment by tracywalker** [comment]
moved to iris_firefox

**Comment by pavelciapa** [comment]
new url: https://github.com/mozilla/iris_firefox/issues/3222
