### ISSUE TITLE
Fix target_offset function

### ISSUE THREAD

**Issue by IonutBudeanu** [mozilla/iris2#77]
During the execution of `disable_search_suggestions` test case it can be noticed that the target_offset functionality doesn't work properly.

Code snippet:

```
 click(show_search_suggestions_in_address_bar_results_checked_pattern.target_offset(-100, 15))
```

In the above example the click needs to be executed at the specific coordinates from the specified pattern but instead the click is performed on it.

**Comment by silviuFlorin** [comment]
there is nothing wrong with target offset. the only change is that image find returns by default the center of the pattern instead of top left corner.
