### ISSUE TITLE
Refactor keyboard API

### ISSUE THREAD

**Issue by mwobensmith** [mozilla/iris2#80]
Since adding the virtual keyboard code, I've noticed that we have a few architectural issues.

There should be only one point of entry into core code if you want to import the keyboard API. Right now we have `api/keyboard/keyboard_api.py`. This is the ideal module to import.

Files that contain "util" in their name or path usually indicate internal usage. They are generally not meant for use or import outside of core code.

Decisions about whether the keyboard API is real (hardware) or virtual ("fake", headless run) should be made inside core code. External modules that import the keyboard API should not have to know anything about the playback environment.

In essence:

* External modules should import `keyboard/keyboard_api.py`.
* The `keyboard_api.py` module should import `keyboard_util.py`.
* The logic inside `xkeyboard.py` should be utilized in `keyboard_util.py` - either by import or by combining the files.
* The `paste` method that exists in `keyboard_util.py` should be moved to `keyboard_api.py`, as it is intended to be used externally.

Optional: 
* Change the naming of the `keyboard` module and/or `keyboard_api.py` file to avoid the redundant naming of "keyboard."  It would be much nicer to see:
```import src.core.api.keyboard```
* Move `key.py` into the above module so that external imports only need to reference one module and not two.

**Comment by rrobotin** [comment]
Hi Matt, 
I've refactored the keyboard (fake and physical) manipulation:

- created a new file `keyboard.py` that contains the keyboard manipulation implementation and also the code that decides what keyboard is used. 

- based on if the '-vk' parameter is used or not the `key_up`, `key_down` and `type` functions from `keyboad.py` are the main functions that can be used/imported for keyboard actions. This functions are the ones that decide which keyboard will be used (fake and physical)

- added the `paste` function in the `keyboard_api.py` file

**Comment by mwobensmith** [comment]
Hi Roxana,

This looks great, and I'm really happy to see that refactored the modules too. :-D

When I run this on Mac, I get an error because the `Xlib` import can't be found, although we are trying to import it. 
```
(iris2) bash-3.2$ iris firefox -t basic
Desired target: firefox
Problems importing module:
No module named 'Xlib'
```
I see that we only install `Xlib` on Linux, according to our `Pipfile`. Should we install `Xlib` on all platforms to avoid this error? Or should we put all imports and code references to `Xlib` inside conditional logic?

I'm guessing it's the latter, as I tried to install the `Xlib` library on Mac via `pipenv install Xlib`, and I get a lot of errors.

**Comment by mwobensmith** [comment]
Fixed
